version: '3.7'
services:
  web:
    build: .
    image: vitty
    ports:
      - 8000:8000
    labels:
      - "traefik.http.middlewares.test-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth=2"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.burst=50"
      - traefik.backend=web
      - traefik.frontend.rule=Host:vittyapi.dscvit.com
      - traefik.docker.network=web
      - traefik.port=8000
    networks:
      - web
    depends_on:
      - traefik
  traefik:
    image: traefik:1.7-alpine
    restart: always
    container_name: traefik
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - traefik.port=8080
networks:
  web:
    external: true